# Generated by Django 4.0.4 on 2022-05-08 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='liked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
