# Generated by Django 4.0.4 on 2022-05-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_like_liked_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['commented_at']},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-liked_at']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='pub_date',
            new_name='commented_at',
        ),
    ]
